# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: stp
#   namespace: ocp-gitops
#   labels:
#     appgrp: stp-apps
# spec:
#   clusterResourceWhitelist:
#     - group: '*'
#       kind: '*'
#   destinations:
#     - namespace: '*'
#       server: '*'
#   sourceRepos:
#     - '*'

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: demo-apps
  namespace: ocp-gitops
  labels:
    appgrp: demo-apps  
spec:
  destinations:
    - namespace: swagger-demo      
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://gsbraman.github.io/stp/'